// Regenerate configopts.h from the real config.json and timer.c, so the fixture cannot drift
// from what the configuration page actually offers. Run before building the C tests.
var fs = require('fs');
var SRC = require('path').join(process.argv[2] ||
    require('path').resolve(__dirname, '..', '..'), 'src');
var cfg = JSON.parse(fs.readFileSync(SRC + '/pkjs/config.json'));

function itemFor(key) {
    var found = null;
    (function walk(items) {
        items.forEach(function(it) {
            if (it.messageKey === key) { found = it; }
            if (it.items) { walk(it.items); }
        });
    })(cfg);
    if (!found) { throw new Error('config.json has no item for ' + key); }
    return found;
}
function selectLines(key, name) {
    var it = itemFor(key);
    var values = it.options.map(function(o) { return parseInt(o.value, 10); });
    return 'static const int32_t ' + name + '[] = {' + values.join(', ') + '};\n' +
           'static const int32_t ' + name + '_DEFAULT = ' + parseInt(it.defaultValue, 10) + ';\n';
}
function colorLine(key, name) {
    var it = itemFor(key);
    return '#define ' + name + ' 0x' + String(it.defaultValue).replace(/^#/, '').toUpperCase() + '\n';
}

// Every item on the page with a message key is a tuple in the dictionary the watch receives
function pageSettings() {
    var count = 0;
    (function walk(items) {
        items.forEach(function(it) {
            if (it.messageKey) { count++; }
            if (it.items) { walk(it.items); }
        });
    })(cfg);
    return count;
}

// Where each contrast mode moves an accent it cannot shade legibly, from the one list jstest.js also
// holds the configuration page to
function movesLines() {
    var moves = JSON.parse(fs.readFileSync(require('path').join(__dirname, 'accent_moves.json')));
    var out = '';
    ['regular', 'high'].forEach(function(mode) {
        var keys = Object.keys(moves[mode]);
        out += 'static const uint32_t MOVES_' + mode.toUpperCase() + '[][2] = {\n';
        keys.forEach(function(from) {
            out += '    {0x' + from.toUpperCase() + ', 0x' + moves[mode][from].toUpperCase() + '},\n';
        });
        out += '};\n';
    });
    return out;
}

var timer = fs.readFileSync(SRC + '/c/timer.c', 'utf8');
var vibe = /#define VIBRATION_LENGTH_MS (\d+)/.exec(timer);
if (!vibe) { throw new Error('timer.c has no VIBRATION_LENGTH_MS'); }

var out = '// generated by gen_configopts.js from src/pkjs/config.json and src/c/timer.c\n' +
          '// do not edit; run `node gen_configopts.js` instead\n\n' +
          selectLines('tenSecondUpdatesAbove', 'TEN_OPTS') +
          selectLines('minuteUpdatesAbove', 'MIN_OPTS') +
          selectLines('instantStart', 'CFG_INSTANT_START') +
          colorLine('timerColor', 'TIMER_COLOR_DEFAULT') +
          colorLine('chronoColor', 'CHRONO_COLOR_DEFAULT') +
          selectLines('contrast', 'CFG_CONTRAST') +
          '#define CFG_PAGE_SETTINGS ' + pageSettings() + '\n' +
          '#define TIMER_C_VIBRATION_LENGTH_MS ' + vibe[1] + '\n' +
          movesLines();
fs.writeFileSync('configopts.h', out);
process.stdout.write(out);
